### API INFO
GET {{nas_host}}/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=all

### CALENDAR API INFO
GET {{nas_host}}/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.Cal.Event

### API LOGIN
GET {{nas_host}}/webapi/auth.cgi?api=SYNO.API.Auth&method=login&version=3&account={{nas_user}}&passwd={{nas_password}}&format=sid&enable_syno_token=yes
Content-Type: application/json

> {% client.global.set("synology_token", response.headers.valueOf('X-SYNO-TOKEN')); %}

### Create a new calendar (with credentials from step above)
POST {{nas_host}}/webapi/entry.cgi
X-SYNO-TOKEN: {{synology_token}}

cal_description=&cal_displayname=calendar_{{$uuid}}&cal_color=#F94B4B&is_hidden_in_list=false&is_hidden_in_cal=false&is_todo=false&is_evt=true&api=SYNO.Cal.Cal&method=create&version=2

> {%
client.global.set("cal_id", response.body.data.cal_id);
client.global.set("original_cal_id", response.body.data.original_cal_id);
%}

### Create event in calendar
POST {{nas_host}}/webapi/entry.cgi
X-SYNO-TOKEN: {{synology_token}}

summary=test-description&cal_id={{cal_id}}&dtstart="TZID={{test_event_timezone_id}}:{{test_event_start_time}}"&dtend="TZID={{test_event_timezone_id}}:{{test_event_start_time}}"&is_all_day={{test_event_is_all_day}}&evt_notify_setting=[]&tz_id={{test_event_timezone_id}}&is_repeat_evt=false&evt_attendee=[]&original_cal_id={{original_cal_id}}&api=SYNO.Cal.Event&method=create&version=2&tz_ical={{test_event_ical_timezone_definition}}

###